# Generated by Django 3.1.2 on 2020-10-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uson', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='ball',
            field=models.SmallIntegerField(verbose_name='Количество баллов'),
        ),
    ]
