# Generated by Django 3.1.2 on 2020-11-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uson', '0002_auto_20201029_1350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['id'], 'verbose_name': 'список достижений', 'verbose_name_plural': 'список достижений'},
        ),
        migrations.AlterField(
            model_name='users',
            name='messager',
            field=models.TextField(error_messages={'required': 'это поле обязательно'}, verbose_name='Текст сообщения'),
        ),
    ]
